# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jaime Declutters"
# fill in description to get description
# description:
email: jaimedurheim@gmail.com
#blog logo
logo: "/assets/images/jd_logo.jpg"
# blog cover
cover: "/assets/images/ceiling.jpg"

name: 'Jaime Durheim'
author: 'Jaime Durheim'
author_image: "/assets/images/author.jpg"

timezone: America/Chicago

permalink: /blog/:categories/:year/:month/:day/:slug/

paginate:	5
paginate_path: "/blog/page:num/"

url: "https://jaimedeclutters.github.io" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
