title: Jaime Declutters
description: "A Home Without Clutter: Spacious, Organized, & Easy To Maintain"
email: jaimedurheim@gmail.com
logo: "/assets/logo/logo-full-435x165.png"

name: Jaime Durheim
author: Jaime Durheim

timezone: America/Chicago

permalink: /:categories/:slug/

url: "https://www.jaimedeclutters.com"
baseurl: ""

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
