# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

title: "Jaime Declutters"
description: Removing Clutter So You Can Pursue An Awesome Life
email: jaimedurheim@gmail.com
logo: "/assets/images/jd_logo.jpg"

name: 'Jaime Durheim'
author: 'Jaime Durheim'

timezone: America/Chicago

permalink: /:categories/:slug/

url: "https://www.jaimedeclutters.com" # the base hostname & protocol for your site
baseurl: ""
